name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      -name: Simple JS action
       id: 
       uses: actions/hello-world-javascript-action@v1
       with:
         who-to-greet: Kaushik
       
